version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - chatbot-net

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot-net

networks:
  chatbot-net: